#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../dist/package.json');
const pkg = JSON.parse(fs.readFileSync(filePath));

pkg.name = '@sumup-oss/foundry';

fs.writeFileSync(filePath, JSON.stringify(pkg, null, 2));
